services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gql-schema
    volumes:
      - gql-schema-data:/var/lib/postgresql/data

volumes:
  gql-schema-data:
